server.port=8080
logging.level.root=ERROR
logging.level.org.springframework.boot=ERROR
logging.level.your.package=ERROR
management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.prometheus.enabled=false
management.metrics.export.prometheus.enabled=false
management.endpoint.health.show-details=always
management.server.port=8080